services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
  grafana-renderer:
    image: grafana/grafana-image-renderer:v4.1.0
    ports:
      - 8081:8081
    environment:
      ENABLE_METRICS: "true"
