services:
  grafana:
    user: root
    container_name: "datalabhell-grafanareporter-app"

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-12.1.}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/datalabhell-grafanareporter-app
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/datalabhell-grafanareporter-app

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.datalabhell-grafanareporter-app:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: datalabhell-grafanareporter-app
      GF_RENDERING_SERVER_URL: http://grafana-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
